name: Lint-check

on:
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Python Linting
        uses: WhyNotHugo/python-linting@v1.0.0
